version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:8000}
    depends_on:
      - backend
    networks:
      - app-network

  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    environment:
      - ENVIRONMENT=test

networks:
  app-network:
    driver: bridge
